### ISSUE TITLE
Open Notebook within an IFrame

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#100]
We may want to consider opening a Jupyter Notebook within an IFrame, or set it as a configuration option.

Jupyter Notebooks are currently opened as a new browser tab which changes the URL. However, not all cases merit opening the Jupyter Notebook in an IFrame, such as is the case where users would like to configure opening a Notebook as soon as they log into the application, similar to JupyterHub.

**Comment by johngriebel** [comment]
I think we decided to forego this.
