### ISSUE TITLE
Obfuscate server endpoints within user interface

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#102]
Provide an Icon or friendly link to open user server. Raw format could be intimidating.

So instead of:

`https://dev-api.3blades.ai/v1/admin/projects/8f58ea26-8ea0-40df-a551-b6a95d4e6a00/servers/8b476be5-4324-413a-b2e6-1992b830f295/endpoint/jupyter/tree`

We could have a 🚀  emoji or a [open my server](
https://dev-api.3blades.ai/v1/admin/projects/8f58ea26-8ea0-40df-a551-b6a95d4e6a00/servers/8b476be5-4324-413a-b2e6-1992b830f295/endpoint/jupyter/tree) link.

**Comment by johngriebel** [comment]
Done.
