### ISSUE TITLE
Golang images self building.

### ISSUE THREAD

**Issue by jkp85** [3Blades/3blades#107]
Currently all our golang binaries (docker-events, core-server) are built in travis and then copied to docker images. I think we should move build process to image itself. Latest docker allows us to do that via [multi stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) This way we could move building images to docker hub and we can build an image on test server without installing Go.

**Comment by johngriebel** [comment]
@roachmd - What are your thoughts on this?
