### ISSUE TITLE
Back office billing system

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#108]
Billing system should include:

- Back office portal to manage packages, should interface with Stripe and our own application
- Metering service to calculate GB / hr for running servers, regardless of the server type being run
- Metering service to calculate GPU or CPU instance types

Future versions could meter disk space usage, bandwidth, etc.

TODO: add downstream issues:

- [x] app-backend
- [x] react-frontend
- [x] cli-tools
- [x] server/controller to calculate GB/hrs, if not part of the above repos

**Comment by johngriebel** [comment]
Closing as done. Still requires testing, however.
