### ISSUE TITLE
When creating a superuser the following warning is displayed while using elastic search

### ISSUE THREAD

**Issue by roachmd** [3Blades/3blades#116]
/srv/env/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py:71: UserWarning: Connecting to search-prod-es-blue-p4z4wjiyntttupv5p32iky6s7u.us-west-2.es.amazonaws.com using SSL with verify_certs=False is insecure.
--
21:40:28 |   |   | 'Connecting to %s using SSL with verify_certs=False is insecure.' % host)
21:40:28 |   |   | /srv/env/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

**Comment by johngriebel** [comment]
Closing as we have switched to a cloud provider for Elasticsearch, making this issue invalid.
