### ISSUE TITLE
Improve webhook clarity and functionality

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#117]
Webhooks are currently implemented for Slack integrations but are not generic. We should organize webhooks like so:

- **Organization webhooks**: Organization webhooks allow you to receive HTTP POST payloads whenever certain events happen within the organization. For example, a user creates a new project. This action should create an event which is sent to the organization webhook. Sending the payload to the organization webhook would allow users to subscribe to activity feeds, receive notifications, or trigger any other action.
- **Project (repository) webhooks**: these are *third party* webhooks used to send event payloads to third party services, such as Slack, when certain actions occur. These are commonly used for notifications.
- **Triggers webhooks**: webhooks could be added to triggers, so that others can call these webhooks to trigger defined actions.

This is probably going to require we add `Events` to our API. [GitHub](https://developer.github.com/webhooks/#events) and [Docker Cloud](https://docs.docker.com/apidocs/docker-cloud/#docker-cloud-events) provide good examples.

/cc @roachmd

**Comment by jkp85** [comment]
@jgwerner All of the above is possible with triggers and actions. Events in docker are basically our actions. We don''t have organisations implemented, so there can't be activity feed for this.
