### ISSUE TITLE
Allow users to select resource type when creating resource

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#129]
Users should be able to select the image they would like to use to create a new server. Right now the image is restricted to `3blades/datascience-notebook` and adding all languages and frameworks to that image type is difficult to maintain.

User facing applications should just obtain a list of available options and display the options to the user with a label. 

Server options should contain:

- Label (framework and/or language)
- Server size in GB
- Jupyter, Restful or Cron

/cc @johngriebel I'm going to leave assignment up to you since I'm not sure of exactly what downstream implications are.

**Comment by johngriebel** [comment]
@jgwerner Okay. I think you're referring specifically to _image_ type, not resource types necessarily. My initial thought here is to add a database table that lists the types of images we have available, and clients can pull from that table to populate the dropdown, or whatever the corresponding functionality might be for a given client.

@jkp85 @raygesualdo thoughts?

**Comment by jkp85** [comment]
@johngriebel I wouldn't go with database table. I would rather go with image creation on demand. For example user have an image (ex. [datascience](https://hub.docker.com/r/jupyter/datascience-notebook/)). From this image we can create our own on the fly (during server start phase) and save it to our image registry. This image would look like:
```
FROM 3blades/core-server AS core
FROM jupyter/datascience-notebook
COPY --from=core runner /runner
EXPOSE 8080 (our runner proxy port)
```
We can even show list of available images pulled from our repo.

**Comment by johngriebel** [comment]
@jkp85 That's fine with me, as long as it's easy for clients (e.e react-frontend) to list the available images.

**Comment by raygesualdo** [comment]
Sounds right to me. We're already do that with the server sizes.

**Comment by jgwerner** [comment]
@johngriebel @jkp85 the tests I have run for custom images follow the example above. I have successfully tested with multiple types, including `tensorflow/tensorflow:gpu`. However, because image is hardcoded into UI (3blades/datascience-notebook) we can't select other images. So in addition to resources (GB for user server), user should select image they would like to spawn. In this case we could start with a set of images as a list, then add functionality for custom images later.

**Comment by johngriebel** [comment]
@jgwerner right. So the end goal here is: "Have a drop down list of available images the user can select for their server", right? Then later, as a separate issue, we can add functionality for custom images.

**Comment by jgwerner** [comment]
@johngriebel correct.
