### ISSUE TITLE
Restful Server Type not correctly validating schema.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#13]
Verify:

- Changing "timestamp" attribute in the request for whatever other name and the requests gets processed as if everything was ok.
- Changing the data attribute with datax simulating a typo, and the requests gets processed ok. Same with using dat (an incomplete name attribute).

**Comment by johngriebel** [comment]
Needs re-tested.

**Comment by johngriebel** [comment]
Closing due to age.
