### ISSUE TITLE
Migrate from OpenResty to Traefik

### ISSUE THREAD

**Issue by johngriebel** [3Blades/3blades#130]
Due to several issues that include things such as lack of readability and maintainability, incompatibility with our Jupyter configurations, and general lack of organization enthusiasm, it has been decided to use Traefik as our reverse proxy instead of OpenResty. This will, of course, require the creation of a new repository. Other tasks will be added as separate issues and linked here as they arise.

- [x] Create new repo for traefik
- [x] Create new repo for nginx, as it is now needed to serve avatars

**Comment by johngriebel** [comment]
Closing, as we were able to add RStudio without changing to Traefik. We may still do this in the future, however.

**Comment by jkp85** [comment]
@johngriebel We don't, my solution won't work without treafik. Routing won't work.

**Comment by jkp85** [comment]
Steps to make it work with two servers:
On userspace server:
1. Create a network that will connect traefik to user server containers (env var `DOCKER_NET`). Driver of that network should be `overlay` if userspace docker is swarm or `bridge` if it is not.
```
docker network create tbs-net
```
2. Set `DOCKER_NET` env var in app-backend [env file](https://github.com/3Blades/app-backend/blob/master/env).
3. Run traefik instance. Traefik need to be run with `DOCKER_NET` network like:
```
docker run -d \
-p 80:80 -p 8080:8080 \
--net=${DOCKER_NET} \
traefik \
-l DEBUG \
-c /dev/null \
--docker \
--docker.domain=3blades.ai \
--docker.endpoint=tcp://172.18.0.1:3376 \ # this is manager address or just docker server address
--docker.watch \
--web
```
In details it is documented here: https://docs.traefik.io/user-guide/swarm/
4. Set app-backend [traefik backend server](https://github.com/jkp85/traefik/blob/master/traefik.toml#L135) to above traefik instance like: 
```
[backends]
  [backends.userspace]
    [backends.userspace.servers.manager_1]
    url = "http://<traefik_endpoint>:80"
```
