### ISSUE TITLE
Confirm required image size when uploading Avatar.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#137]
When adding a new Avatar, if the image is too large the system returns a message stating: `The image is too large`. We need to specify the maximum image size and preferably suggest how the image should be formatted, for example, state that it should be a square of X pixels by X pixels.

**Comment by johngriebel** [comment]
@raygesualdo didn't you push a fix for this a bit ago?

**Comment by raygesualdo** [comment]
Yeah, the error message should read "Your avatar cannot be larger than 100kB."

**Comment by raygesualdo** [comment]
@jgwerner Which env are you using?

**Comment by jgwerner** [comment]
@raygesualdo production

**Comment by johngriebel** [comment]
@raygesualdo @jgwerner what's the status on this?Just a fix that needs to be deployed to production?
