### ISSUE TITLE
Duplicate project by creating a fork.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#14]
Now that we have adding Git to the file system in the backlog, we also need to consider adding the ability to fork projects.

Put simply, this avoids having to copy and move individual files from one project to another. A work around would be to move resources using third party services to and from 3Blades file system, but that's an inefficient work around.

Adding Git to the file system should be high on the priority list to be able to add this new feature.

#15

**Comment by jgwerner** [comment]
Related to git support #15

**Comment by johngriebel** [comment]
Closing as this will be part of the native git support epic.
