### ISSUE TITLE
Lack of notification for an expired Trial account

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#142]
Once an account has expired and a user attempts to access the system there aren't any notifications telling the user that the account has expired.

**Comment by johngriebel** [comment]
@gwerner this is already being implemented as part of 3blades/app-backend#432

**Comment by jgwerner** [comment]
@johngriebel would frontend reflect those changes automatically in the UI? It seems that we would have to have a 3blades/react-frontend issue open as well to define behavior.

**Comment by johngriebel** [comment]
@jgwerner If we want to have a banner at the top of their homepage or something, then yes there will need to be a react-frontend issue. Otherwise, they will have a notification in their feed (as well as an email).

**Comment by johngriebel** [comment]
Closing this as the only remaining issue, 3blades/react-frontend#311, is reiterated in #146.
