### ISSUE TITLE
Update notifications for expired Trial accounts and invalid subscriptions

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#146]
When Trial accounts expire, users are sent notifications that their credit card / debit card could not be charged. We should send this notification only when a user has an active subscription and the billing information is invalid when attempting to make a charge for said subscription.

Expired Trial accounts should trigger a notification telling the user that their Trial account has expired and contain Call To Action to upgrade account to a paid version, which would unlock options, in particular being able to spawn servers.

Users should also receive notifications within the front end that the Trial account has expired. 

Finally, users should receive a notification within the front end and CLI Tools that the server could not be started because either:

1. Trial account expired and user no longer has credit to spawn a server
1. User has used all available credits to spawn user servers (Trial or paid subscription)

Right now the system returns a `402` error when attempting to start a server when an account has expired, but the error is not surfaced in the frontend:

```
Failed to load resource: the server responded with a status of 402 (Payment Required)
logic.js:22 Error: Request failed with status code 402
    at t.exports (https://app.3blades.ai/static/js/main.a9a59157cfe824c88a0c.js:1:169896)
    at t.exports (https://app.3blades.ai/static/js/main.a9a59157cfe824c88a0c.js:1:493681)
    at XMLHttpRequest.d.(anonymous function) (https://app.3blades.ai/static/js/main.a9a59157cfe824c88a0c.js:1:168908)
```

**Comment by johngriebel** [comment]
@jgwerner we should be careful about the language surrounding telling the user they cannot start a server due to a trial account - we aren't generating notifications for each of those events (unless you feel that we should be). We're simply telling the user why they cannot start a server.

**Comment by johngriebel** [comment]
@jgwerner can this be closed? All of these notifications have been migrated to the appropriated places, correct?
