### ISSUE TITLE
Reset login credentials defect

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#147]
There is a bug to reset login, first reported by an end-user. I was able to replicate the bug by following these steps:

- Click on `Forgot Password`.
- User receives email with URL: `http://3blades.ai/auth/password-reset?uid=<uid goes here>&token=<token goes here>`.
- User clicks on URL and user is shown standard login screen, not a prompt to type in a new password and confirm it.

**Comment by johngriebel** [comment]
This was fixed in 3blades/devops#115.
