### ISSUE TITLE
Any user can delete project on public accounts

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#168]
Any user can delete a public project, even if they are not a collaborator.

**Comment by jgwerner** [comment]
@john @nathanielcompton we got this error although it may be from projects created prior to the major update. More testing is needed.

**Comment by johngriebel** [comment]
@jgwerner can you provide the data you tested with? e.g. project name, user you were logged in as, etc? The code does check to make sure the authenticated user is the owner of the project before deleting.

**Comment by jgwerner** [comment]
@johngriebel I don't recall the project name but it was with the admin user. I would like to enroll a new user to retest but am unable to do so. Registration error is here #169

**Comment by jgwerner** [comment]
@johngriebel closing. Validated that error does not appear with new projects added after the major update.
