### ISSUE TITLE
Sign up option disabled when attempting to enroll for a new account

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#169]
To replicate, navigate to [PR deployment](https://deploy-preview-359--threeblades-webui-blue.netlify.com/auth/register) for `react-frontend` PR 3blades/react-frontend#359.

**Comment by raygesualdo** [comment]
It's disabled until all of the fields are filled in correctly, but the error messages aren't showing up right now. We should probably enable the button. The errors will show once they click it.

**Comment by jgwerner** [comment]
@raygesualdo I filled in the fields correctly, there is a 500 error in the console. Cleaned cache and tried with both Chrome and Safari.

From console:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by raygesualdo** [comment]
Just worked for me 😕

**Comment by johngriebel** [comment]
@jgwerner can you provide an example of the data that produces the error? I'm able to register, activate, and log in.

**Comment by jgwerner** [comment]
@johngriebel @raygesualdo any data. I think I am able to replicate the error consistently (regardless of the computer) with the [PR deployment URL](https://deploy-preview-359--threeblades-webui-blue.netlify.com).

I re-tested on two other computers with Mac OSX Sierra with Chrome / Safari. Same behavior from the office and from home. Sign up appears when navigating to registration page after clicking on `Sign Up` in `../auth/login` page:

![sign_up_appears](https://user-images.githubusercontent.com/920170/32471543-dd789190-c32b-11e7-84d3-ba59631e1cce.gif)

`Sign Up` button is not activated when navigating directly or refreshing the registration page:

![signup_deactivated](https://user-images.githubusercontent.com/920170/32471659-84f94dec-c32c-11e7-982c-9e487e25757e.gif)

**Comment by roachmd** [comment]
I was able to replicate the issue here at the link below::
https://deploy-preview-359--threeblades-webui-blue.netlify.com/auth/register

NOTE:: 
The issue seems to be when you don't put in a valid password...you don't get a warning or notifications its invalid. When you put in a valid password you get through

**Comment by jgwerner** [comment]
@roachmd confirmed I was able to replicate that scenario too.

**Comment by johngriebel** [comment]
@jgwerner @raygesualdo So I guess the action item here is to display an error to the user when they have entered an invalid password?

**Comment by raygesualdo** [comment]
Closing since 3blades/react-frontend#364 is closed.
