### ISSUE TITLE
Project name error after copying project

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#170]
After copying a project and navigating to Project --> Settings, the original project name appears in the project name field.

![screen shot 2017-11-06 at 4 36 07 pm](https://user-images.githubusercontent.com/920170/32465199-aad32dba-c310-11e7-95bd-17610a05dc29.png)

**Comment by raygesualdo** [comment]
I've already PRed a fix for this: 3blades/react-frontend#362.

**Comment by jgwerner** [comment]
@raygesualdo I'm going to temporarily reopen this issue since blue is merging from master. If master has been updated with this fix I would assume that it should be reflected in the blue PR deploy, right?

**Comment by johngriebel** [comment]
@jgwerner it looks like the fix has not been merged yet; it's awaiting code review. I'll link the react-frontend issue to this one.

**Comment by jgwerner** [comment]
@johngriebel @raygesualdo you guys are right, the PR had not been merged yet. Just added my review w/ approval. Closing.
