### ISSUE TITLE
Allow hyphens when changing a project name

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#176]
Changing a project name does not allow for hyphens. We should support being able to add hyphens to project names.

I'm opening this as a bug because Projects that are copied have hyphens.

![project_hyphen_error](https://user-images.githubusercontent.com/920170/32522055-c36cf4ae-c3e3-11e7-8627-54491bc3f23a.gif)

**Comment by jgwerner** [comment]
[In dev](https://dev.3blades.ai) user does not receive the error but upon saving by clicking on the Update button user does not receive confirmation message and name does not change.

![project_name_error2](https://user-images.githubusercontent.com/920170/32523010-987c92b4-c3e7-11e7-9ef6-8501ee66752e.gif)

**Comment by johngriebel** [comment]
Done
