### ISSUE TITLE
Empty items for search results

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#180]
Sometimes a search with return empty items in the dropdown results. If clicked, the user sees a page not found error message since the item is `null`. Null items returned from the search should be hidden from view.

![search_error](https://user-images.githubusercontent.com/920170/32618708-731e4232-c546-11e7-98b6-d815c17777a7.gif)

**Comment by johngriebel** [comment]
Closing since this was fixed as part of 3blades/app-backend#547.
