### ISSUE TITLE
Upload multiple files

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#25]
Users will most likely want to upload multiple files at once. Otherwise they will have to open file upload dialogue box on multiple occasions to upload multiple files.

Larger files (bigger than 10 or 15 Mbytes or so) should not be able to be uploaded via web interface. Larger files could be imported with AWS S3 integration or CLI Tools. In all cases users should be shown progress during upload and final upload status via notifications (banner, etc).

**Comment by jkp85** [comment]
Related to 3Blades/cli-tools#48

**Comment by jgwerner** [comment]
Done.
