### ISSUE TITLE
Edit first name, last name and user name after logging in with OAuth credentials.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#29]
First Name and Last Name must be set as public attributes for OAuth to work with app-backend.

If the First Name and Last Name are set to be optional attributes, then the user would not be forced to have First Name and Last Name as public attributes in the third party OAuth providers, such as GitHub and Google+.

Once the user attempts to login with OAuth and assuming the user is authenticated after confirming permissions, then a web form should appear so that the user can confirm:

- First Name
- Last Name
- User ID

Since the user's identifying attribute for OAuth is the email, then this attribute would be read only.

**Comment by johngriebel** [comment]
This feature exists by default.
