### ISSUE TITLE
Collaborator search fixes

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#30]
Two issues:
- [ ] Search can throw duplicated results.
- [ ] When searching by email, results either 1) Don't have anything to do related to the search input or 2) Don't five the user any way to know if the displayed user name corresponds with the input email.  

TODO: add expected behavior.

**Comment by jkp85** [comment]
I think we should use django haystack with elasticsearch as backend. This will be most versatile in the future.

**Comment by jgwerner** [comment]
Duplicate
