### ISSUE TITLE
Use project-files directory name instead of workspaces.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#31]
A more generic folder name for user or team resources would help ease potential confusion. Proposal is to change directory from `/workspaces` to `/project-files`.

The `/workspaces` directory name was inherited from when we only had workspaces available in the platform.

**Comment by johngriebel** [comment]
@jgwerner is this still relevant/something we want to do?

**Comment by jgwerner** [comment]
@johngriebel it's really not that important. It's an under the hood adjustment that would not add a lot of value to the user. However, it is possible that in the future support staff or admin users would get a little confused by the folder name. So my vote is to put this on hold for now.

**Comment by johngriebel** [comment]
Okay, I'll leave it open for now. I think this may become part of the discussion when implementing teams.

**Comment by johngriebel** [comment]
Closing.
