### ISSUE TITLE
User registration flow.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#32]
Local Account registrations are confirmed by clicking on a confirmation that is sent via email.

OAuth accounts registrations are confirmed after an OAuth account introspection.

In both cases, a Form should be added so that the user can confirm his or her username before proceeding to first log in.

![3blades - login and register - login and register 1](https://cloud.githubusercontent.com/assets/920170/22753309/b0cb0562-ee09-11e6-9ff5-af95b9f97028.png)

**Comment by johngriebel** [comment]
Closing this as done.
