### ISSUE TITLE
Add collaborators with matching search strings

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#42]
Search implementation for new collaborators looks for users by first name, last name, user id and/or email domain name. All return the user id for the user if he or she exists in the system.

The system should return a limited number of results based on matching strings. If a user were to type `myuser` then the system should return a list of users that match to that string. For example, typing `smith` should display a list of users that have `smith` in the user name, first name, last name or email address.

The list should return user avatar, user name and full name if applicable. Full name may not be available in user's public profile.

**Comment by jkp85** [comment]
This is part of the search system

**Comment by jgwerner** [comment]
Reference: https://django-haystack.readthedocs.io/en/v2.6.0/

**Comment by jgwerner** [comment]
Related to #76

**Comment by jgwerner** [comment]
Done.
