### ISSUE TITLE
Deleting user or team account should also delete all associated data. 

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#43]
When a user deletes an account from the Account Settings --> Delete Account option or from the Admin console, all user and/or team information should be deleted along with the account itself. 

This includes but is not limited to:

- User integration settings
- User project files
- User servers
- SSH Keys and API Keys
- Integration settings

If the user is the owner for Team accounts, a text message in the Delete Account option container should display:

> Delete Account
> Your account is currently an owner of these Teams: <Team Name>
> You must transfer ownership or delete these organizations before you can delete your account.

Before allowing the user to delete their account, they need to confirm deletion with a modal:

> Delete Account
> Are you sure you want to delete your account? This process is irreversible. All account settings, project files and workspaces will be eliminated. Please back up your data before proceeding. To proceed, type DELETE in the text box below.
> Cancel | OK
- Since user project files are not stored in the database, a separate task needs to be executed to delete folders and files related to that user.
- Workspaces, if currently in the run state, would need to be stopped and terminated and then culled from the system.
- Temporary data, such as cookie session keys need to be deleted as well.

**Comment by jgwerner** [comment]
SQL script proposed by @netoisc:

...while, we can use this script to delete all the user's relationships:

```
DELETE
FROM user_groups
WHERE user_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM projects_users
WHERE user_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);


DELETE
FROM project_workspace_server
USING project
WHERE
  project_workspace_server.project_id = project.id
  AND (NOT exists(
      SELECT 1
      FROM projects_users
      WHERE project.id = projects_users.project_id
  ) AND NOT exists(
      SELECT 1
      FROM projects_teams
      WHERE project.id = projects_teams.project_id
  )
  );

DELETE
FROM team_member
WHERE member_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM team_watch
WHERE user_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM team_groups
USING team
WHERE
  team_groups.team_id = team.id
  AND team.created_by_id IN (
    SELECT "user".id
    FROM "user"
    WHERE username = 'gwerner1'
  );

DELETE
FROM projects_teams
USING team
WHERE
  projects_teams.team_id = team.id
  AND team.created_by_id IN (
    SELECT "user".id
    FROM "user"
    WHERE username = 'gwerner1'
  );

DELETE
FROM project_workspace_server
USING project
WHERE
  project_workspace_server.project_id = project.id
  AND (NOT exists(
      SELECT 1
      FROM projects_teams
      WHERE project.id = projects_teams.project_id
  ) and NOT exists(
      SELECT 1
      FROM projects_users
      WHERE project.id = projects_users.project_id
  ));

DELETE
FROM followers
WHERE follower_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM followers
WHERE followed_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM synced_resource
USING integration
WHERE
  synced_resource.integration_id = integration.id
  AND integration.user_id IN (
    SELECT "user".id
    FROM "user"
    WHERE username = 'gwerner1'
  );

DELETE
FROM integration
WHERE user_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM "group"
WHERE NOT exists(
    SELECT 1
    FROM user_groups
    WHERE group_id = "group".id
) and NOT exists(
    select 1
    from team_groups
    where group_id = "group".id
);

DELETE
FROM "group"
WHERE NOT exists(
    SELECT 1
    FROM team_groups
    WHERE group_id = "group".id
);

DELETE
FROM project
WHERE NOT exists(
    SELECT 1
    FROM projects_users
    WHERE project_id = project.id
)and NOT exists(
    SELECT 1
    FROM projects_teams
    WHERE project_id = project.id
);


DELETE
FROM "email"
WHERE user_id IN (
  SELECT "user".id
  FROM "user"
  WHERE username = 'gwerner1'
);

DELETE
FROM "user"
WHERE username = 'gwerner1';
```

**Comment by jgwerner** [comment]
We should't delete data but flag it as inactive. Storing data for later use would be good for our own analytics endeavors.

**Comment by johngriebel** [comment]
Not applicable anymore.
