### ISSUE TITLE
Kanban board to manage project assets

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#47]
This feature would make it simple for users to be able to collaborate on project resources and add a status for each file. Technically, they could be labels but the ability to see the project status within Kanban style boards is easy to digest. For now, no additional information (meta data) can be added to the file via the workflow option. Adding the status label would be done when editing the file itself.

The Kanban boards for now are static: 
- On Hold
- In Progress
- In Review
- Approved

Personal wireframe:

https://www.lucidchart.com/documents/edit/ed0933dc-33fb-4478-b34f-111d10c35216/42

Team wireframe:

https://www.lucidchart.com/documents/edit/ed0933dc-33fb-4478-b34f-111d10c35216/43

**Comment by jgwerner** [comment]
Not adding to milestone at this time. Will look into integrating with Trello / Asana first, however if the development cost is low for an MVP we could consider it for later in 2017.

**Comment by johngriebel** [comment]
Closing as this will receive more specification in the near future
