### ISSUE TITLE
Enable project setting editions.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#50]
Users should be able to make projects private, transfer ownership for the project or delete the project if they choose to do so, assuming they have the permissions that would allow them to do that. Users that don't have these options should not have the Settings menu option enabled.

**Comment by jgwerner** [comment]
This should also be considered within CLI Tools.

**Comment by jgwerner** [comment]
Verify tests in Runscope.

**Comment by johngriebel** [comment]
Done.
