### ISSUE TITLE
Activity feed.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#51]
Viewing an activity feed for the project is useful when the user wants to quickly view project updates directly from within a project. An activity feed in a dashboard my be convoluted  with other updates, such as notifications about the profiles a user follows, conversations they are watching or that they have starred, etc. This option allows the user to see projects related specifically for the project they are viewing and / or editing.

Stream.io seems to offer good integration options.

**Comment by jgwerner** [comment]
Although placed in the 2.x milestone, needs revisiting. I have my doubts about perceived value.

**Comment by johngriebel** [comment]
Closing for now. Seems to be redundant with notifications.
