### ISSUE TITLE
Notifications center

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#52]
Notification center should have two tabs: one where the user can view the messages that are related to the projects that he or she follows or for conversations that he or she is a part of. Within the notifications tab sections should include:

- Unread: all notifications that have not been read.
- Participating: all notifications that have been sent, where the user is part of the conversation or the user has been mentioned with the @mention. 
- All Notifications: both notifications of other resources that are being watched and notifications where the user is part of a conversation.

**Comment by jgwerner** [comment]
These notifications are different from the email communications received from the system related to account information. These notifications refer to notifications about items that the user follows, such as projects, files, etc.

User should have the option to receive notifications for all items that they are 'Watching' which is synonymous with 'Following'. (Following concept is only applied to profiles that are followed, i.e. other users, Watching concept applies to other resources that are followed, such as Projects and Teams).

Sections should include:

- Automatic Notifications: option to automatically Watch resource when user is added to resource, such as when a user is invited to participate in a project.
- Participating: option to receive notifications via email, web or both when a user is part of a conversation or when a user receives a @mention.
- Watching: updates to any project that the user is watching. Like the participating option, should include updates via web, email or both.

**Comment by johngriebel** [comment]
Closing as no longer applicable.
