### ISSUE TITLE
Try and buy registration

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#54]
Registration workflow:

- User clicks on Free Trial, Sign Up, etc on web page
- Email is sent
- Activate Account confirmation page
- Login to main account page

Notes:

- Email registration confirmation token should only be able to be used once.
- Email registration sender should be an alias: clientservices@3blades.io
- Email registration should have 3Blades branding.

Enrolling for a trial account in the strict sense of the word means that a user has most if not all features enabled. At the end of the trial period the user would be prompted to upgrade to a paid account, if not, then the user would be automatically downgraded to a free account, if applicable.

**Comment by jgwerner** [comment]
This is part of the billing system and will be specified with independent sub-issues.

**Comment by johngriebel** [comment]
Closing this as done.
