### ISSUE TITLE
Visualization Dashboard for 3Blades services

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#57]
Visualization dashboard for all application assets. This would include things like visualizations for running models, job results, workspace uptime, server use per collaborator, among others.

**Comment by jgwerner** [comment]
Use docker visualization dashboards.

**Comment by jgwerner** [comment]
There are several alternatives to view visualizations for Docker services including [Grafana](https://grafana.com/get), among others. This would be a nice feature so that users can view resource usage, project patterns, etc.

**Comment by johngriebel** [comment]
Closing for lack of specification for now.
