### ISSUE TITLE
Eezzy Helper Service

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#66]
The alternative is to offer Eezzy as a stand-alone library, however, offering this as a service would allow 3Blades to enrich the experience with better performing models, faster iteration times, and better distribution. Additionally, it allows the product to offer an additional entry point for monetization, i.e. if users would rather use local environments or a third party system to manage their data science projects, they could still use 3Blades' data science optimization services.

This epic deals with developing and deploying the first version of a data science recommender engine. This is the first level of abstraction so that future Eezzy's can inherit from this service. Generally speaking, this abstraction should deal with:

1. General infrastructure requirements
1. Recommendations for data science tasks
1. UI / CLI tools UX
1. Documentation

This Epic deals with the prototype only.

**Comment by jgwerner** [comment]
Modified scope for all sub-issues. Instead of calling RESTful service, local python sklearn wrapper library will be used first for the prototype.

**Comment by johngriebel** [comment]
@jgwerner is this still something we want to do? My guess is no.

**Comment by jgwerner** [comment]
@johngriebel Correct.

**Comment by johngriebel** [comment]
Closing.
