### ISSUE TITLE
Manage server life cycle states with triggers

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#69]
This issue deals with how to manage server life cycle states.

This is a general specification for triggers to manage server states. Servers are managed as a service, which is a natural definition since we are using Docker Swarm Mode services to manage user servers. We need to define specific commands for [API](https://github.com/3blades/app-backend), [CLI Tools](https://github.com/3blades/cli-tools) as sub-issues.

Triggers are URLs that will start an action of the service whenever a POST request is sent to them. No authentication tokens should be required. The ability to revoke triggers should exist for security reasons. Example use cases could be:

- A spark job finishes and that event is sent as a POST to a 3Blades unique URL (a.k.a. webhook) which represents the resource uri to start a specific Jupyter Notebook server
- An updated image is available in DockerHub and the user decides to redeploy server based on new image update automatically. 

Triggers should have UUIDs associated with them. Services have their own UUIDs. Thus, in some cases the `resource_uri` contains both the service UUID and the trigger UUID in the `resource_uri`.

Attributes:

- url: address to be used to call the trigger with a POST request
- name: a user-provided name for the trigger
- operation: the operation that the trigger call performs (see table Operations below)
- resource_uri: a unique API endpoint that represents the trigger. Otherwise known as webhook. The resource_uri should 

Operations:

START: performs a redeploy service operation.
STOP: performs a scale up service operation.
REDEPLOY: restarts a service restart operation.
TERMINATE: terminates a service operation.
SCALEUP: scales up a service operation.

> Note: restarting a service task is a flag that is set when creating service with Swarm Mode.

**List Triggers**

- Lists all current triggers the service has associated to. Returns a list of Service Trigger objects.

HTTP Request

- GET /{namespace}/service/{service_uuid}/triggers/

Path Parameters

- service_uuid: the UUID of the service the triggers are associated to. As mentioned above, service = server service, since this is inline with Docker Swarm Mode concepts.

**Create a new trigger**

- Creates a new service trigger.

HTTP Request

- POST /{namespace}/service/{service_uuid}/trigger/

JSON Parameters

- name: (optional) A user provided name for the trigger
- operation: (optional) The operation to be performed by the trigger (default: “REDEPLOY”)

Get and Existing Trigger

- Creates a new trigger

HTTP Request

- GET /{namespace}/service/{service_uuid}/trigger/{trigger_uuid}

Path Parameters

- service_uuid: the UUID of the service the triggers are associated to
- trigger_uuid: the UUID of the trigger to retrieve

**Delete a Trigger**

- Deletes a trigger

HTTP Request

- DELETE /{namespace}/service/{service_uuid}/trigger/{trigger_uuid}

Path Parameters

uuid: the UUID of the associated service
trigger_uuid: the UUID of the trigger to delete

**Call a Trigger**

Executes the trigger. For SCALEUP triggers, the number of containers to scale up can be passed at the end of the trigger call url.

HTTP Request

- POST /{namespace}/service/{service_uuid}/trigger/{trigger_uuid}/call

Path Parameters

- uuid: the UUID of the associated service
- trigger_uuid: the UUID of the trigger to call

/cc @johngriebel @jkp85 

#68

**Comment by jkp85** [comment]
@jgwerner what is the difference between `url` and `resource_uri`?
