### ISSUE TITLE
Stripe integration

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#71]
Stripe integration to enable purchases with Web UI and CLI Tools. The first version will focus on CLI Tools using [Stripe's Golang Library](https://github.com/stripe/stripe-go). [API docs](https://stripe.com/docs/api/go) provide some good examples. Once validated as working correctly, the second version can include billing management via web UI.

CLI Tools should allow users to manage administrative tasks, such as managing credit card and billing methods, upgrades or downgrades to the plan, manage teams and switch between personal/org teams when needed. 

For **billing**, the user should be able to add their credit/debit card information and have that processed directly by Stripe. Information should not touch our servers at any point in time. In other words, 3Blades CLI Tools should have Stripe Golang library compiled into it and have payment information routed directly to Stripe servers. Javascript components should be added to front end UI to connect to Stripe servers, directly.

Roles that should be considered:

- Administrative: users need to add, edit and delete plans.
- End users: users should be able to select plans that are available to them for purchase.

The first version(s) can have administrative users use Stripes native web admin console. This information could be synched with our own application and third party services if necessary.

The general workflow consists of:

1. User being notified that their plan will expire or has expired
1. User authenticates into system
1. User selects plan
1. User enters CC information
1. User awaits confirmation. If successful, the user is flagged as active in app-backend DB. Otherwise, the user is notified that payment was not successful and is not updated as 'paid and active' status.

**Comment by johngriebel** [comment]
Done!
