### ISSUE TITLE
Add ability to upload files

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/3blades#74]
Currently, file creation requires uploading the contents of the file as part of the JSON payload. This is inefficient and problematic from multiple perspectives. We need to:

- Add the ability in `app-backend` to upload files (preferably handling multi-file uploads as well) as a `multipart/form-data` form type. This departs from our current JSON-only API, but is a common convention even for JSON-only APIs when needing to upload a file. Some initial documentation for getting this set up can be found [here](https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/) and [here](http://docs.swagger.io/spec.html#4-3-5-file).
- Refactor how the CLI tools are uploading files to accommodate for the new form type.
- Account for "normal" file uploads in the browser (`react-frontend`).

**Comment by jgwerner** [comment]
Done.
