### ISSUE TITLE
Create file watcher

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#75]
Uploading content and files outside of the API would create issues for the system as it stands, since the backend server would not know that the file exists and therefore would not have a reference to it with UUID.

Therefore all files created, deleted or updated outside of the API, such as with Jupyter Notebooks, should update the applications database.

We are proposing a file watcher to poll the file system for updated contents and create and update the application with unique identifiers.

**Comment by roachmd** [comment]
Looking at different libraries for this
 golang version https://fsnotify.org/
 python version https://pypi.python.org/pypi/watchdog

**Comment by raygesualdo** [comment]
nodejs: https://github.com/paulmillr/chokidar | https://github.com/kimmobrunfeldt/chokidar-cli
native (C++ implementation): https://facebook.github.io/watchman/

**Comment by roachmd** [comment]
@raygesualdo  I really do like https://facebook.github.io/watchman/docs/nodejs.html

**Comment by raygesualdo** [comment]
Yeah, been digging into the docs myself. Seems extremely powerful.

**Comment by jgwerner** [comment]
LGTM

**Comment by jgwerner** [comment]
Done.

**Comment by jgwerner** [comment]
@johngriebel @roachmd re opening issue to define configs.

**Comment by johngriebel** [comment]
Done.
