### ISSUE TITLE
Update API to eliminate namespace parameter to manage users.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#80]
Update API to eliminate namespace to manage users.

Replace endpoints that have namespace to have users point to root.

For example replace:

    `/{namespace}/users`

With:

    `/users`

**Comment by jgwerner** [comment]
@roachmd could you validate as completed?

**Comment by roachmd** [comment]
Confirmed. { namespaces } is removed.

/users/profiles/

**Comment by jgwerner** [comment]
Done.
