### ISSUE TITLE
Set transition status until server container is available

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#83]
We need to add a check after a user starts a server (cron, restful or jupyter). Right now the container switches to `Running` immediately even though internal services may not be available.

We need to develop an internal service that asserts that the service is up and running based on type, before allowing the user to view the container's exposed and published port. Otherwise, `502` errors are shown which affect the user experience.

Transition status refers to:

- Stopped --> Starting --> Running
- Running --> Stopping --> Stopped
- Running --> Terminating --> Terminated
- Stopped --> Terminating --> Terminated

**Comment by jgwerner** [comment]
Duplicate of #85

**Comment by johngriebel** [comment]
Implemented in react-frontend.
